### ISSUE TITLE
Strip mixed content rather than converting to escaped characters

### ISSUE THREAD

**Issue by mpaqu-lib** [smith-special-collections/berry-hill-AS-IS-integration#7]
All mixed content should be stripped from the exported content, especially in <note>, <title> and <abstract>, rather than simply escaping the HTML encoding.
For example, instead of:
`  <title>Advertisement for &lt;title render=&#34;italic&#34;&gt;Monday or Tuesday&lt;/title&gt; by Virginia Woolf (No. 17), 1921</title>`
The output should be:
 `<title>Advertisement for Monday or Tuesday by Virginia Woolf (No. 17), 1921</title>`

See smith_1342044_MODS.xml for an example.

**Comment by cmarshall73** [comment]
Fixed in commit bf6b88f69a27150357aea256c1c4e3be202dc65c
